[package]
name = "gateway_addon"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.4.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
