#!/bin/sh

# cd into $SYSROOT so that $PWD is inside the chroot
cd $SYSROOT

# Execute raspbian binaries using the qemu-arm-static emulator, while chrooted
# to the sysroot.
# If we're running as the $RPXC_USER we need to sudo to root to perform the
# chroot, and then drop back down to the user afterwards.
if [ -z "$RPXC_UID" ]; then
    chroot $SYSROOT \
        $QEMU_PATH /bin/sh -c "cd /build && $*"
else
    export HOME=/home/$RPXC_UID
    sudo -E chroot --userspec $RPXC_UID:$RPXC_GID $SYSROOT \
        $QEMU_PATH /bin/sh -c "cd /build && $*"
fi