name: Update Docker Hub Description

on:
  push:
    branches:
      - master
    paths:
      - README.docker.md
      - .github/workflows/dockerhub-description.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_REAL_PASSWORD }}
          repository: webthingsio/gateway
          readme-filepath: ./README.docker.md
