name: Add new issues to the specified project column

on:
  issues:
    types: [opened]

jobs:
  add-new-issues-to-project-column:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-issues-to-organization-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/orgs/WebThingsIO/projects/3
        GITHUB_PROJECT_COLUMN_NAME: Triage
